### ISSUE TITLE
V.PhyloMaker2 phylo tree error

### ISSUE THREAD

**Issue by fab4ap** [flaviomoc/DMSD#3]
I'm trying to use spat.alpha/spat.beta on phylo tree generated by V.PhyloMaker2 and getting errors. I don't see any guidance in the divraster documentation on what type of tree to use for tree/plant species. Here is the code

```
library(V.PhyloMaker2) ; library(dplyr); library(ape); library(divraster); library(terra)
natree = phylo.maker(sp.list = naspp, tree = GBOTB.extended.TPL, output.tree=T, nodes = nodes.info.1.TPL)
write.tree(natree$scenario.3, "natree.tre")

tf = read.tree("natree.tre")
tf = as.phylo(tf)

 p = rast("na_sumPres_actual_stack.tif")
pg = project(p, "+proj=longlat +datum=WGS84")
z = vect("canusmex_geog.gpkg")
ce = ext(z)
pge = crop(pg, ce)
g = spat.alpha(pge) # Works

 g = spat.alpha(pge, tf)

```**Error: [app] cannot use this function
Error in comm %*% A: non-conformable arguments**

```
gb = spat.beta(pge, tf)
Error: [focal] test failed

```

**Comment by flaviomoc** [comment]
Thanks for your feedback! It seems there might be a problem because the 'rast' and 'phylo' objects have different numbers of species. I will try to make them equal. If that does not work, could you please provide a reproducible example? This way, I can better understand and fix the issue.

**Comment by fab4ap** [comment]
Appreciate the quick response! If your fix does not work, I'll try to give you a reproducible example (325 tree species of North America!).

**Comment by fab4ap** [comment]
Hope you have been able to make progress. Attached are the files that can reproduce the error.
Thanks!!

library(terra); library(divraster); library(ape)
pge = rast("na_sumPres_ActualStack.tif")
 tf = read.tree("natree.tre") # Or "natree2c.tre"
 tf = as.phylo(tf)

g = spat.alpha(pge, tf)
gb = spat.beta(pge, tf)
[divraster_phylo_Error.zip](https://github.com/flaviomoc/divraster/files/12784748/divraster_phylo_Error.zip)

**Comment by flaviomoc** [comment]
After checking your data, it appears that the issue is indeed the different species names between the spatraster and phylo objects. The phylo object contains the actual species names, while the spatraster object labels the species as "rivmf_nfif3_20k_sXXX". The updated version of the package now specifies this error, and I am including this information in the functions' documentation. You might want to consider running the code below for further details. Thank you!

## install updated version from github
devtools::install_github("flaviomoc/divraster", force = TRUE)

## load packages
library(terra); library(divraster); library(ape)

## load data
pge = rast("na_sumPres_ActualStack.tif")
tf = ape::read.tree("natree2c.tre") # Or "natree2c.tre"
tf = as.phylo(tf)

## apply functions
g = spat.alpha(pge, tf)
gb = spat.beta(pge, tf)
### Error in inputs_chk(bin1 = bin, tree = tree) : 
###   Species names in 'bin1' and 'tree' must match.

## check objects
sort(names(pge))
sort(tf$tip.label)
### Number of species and their names do not match!

## check divraster examples
bin1 <- terra::rast(system.file("extdata", "ref.tif",
                                package = "divraster"))
tree <- ape::read.tree(system.file("extdata", "tree.tre",
                                   package = "divraster"))
sort(names(bin1))
sort(tree$tip.label)
spat.alpha(bin1, tree)
spat.beta(bin1, tree)

**Comment by fab4ap** [comment]
Thanks! Must have checked that myself - was under the impression that the numbers was also recorded in the tre file. Appreciate your help and the improved error message!

**Comment by flaviomoc** [comment]
Great!
